### ISSUE TITLE
Mutilabel support

### ISSUE THREAD

**Issue by DecentMakeover** [facebookresearch/FixRes#1]
Hi , Thanks for sharing your work , Do you provide multi label support?

Thanks

**Comment by TouvronHugo** [comment]
Hi @DecentMakeover,

Thank you for your question,

The paper does not consider the multi-label case, and the code does not support it. Our approach will very likely improve the accuracy in a multi label case, but we have no plan to try it in the short term.

Hugo

**Comment by DecentMakeover** [comment]
Thanks
