### ISSUE TITLE
About formula (1) in the Paper

### ISSUE THREAD

**Issue by BluebirdStory** [facebookresearch/FixRes#10]
Hi, thank you for this great work!
When I read your paper I was confused by formula (1):

![image](https://user-images.githubusercontent.com/33217105/73232662-e6344b80-41be-11ea-9d51-e116c900fd8d.png)
according to this formula:
![image](https://user-images.githubusercontent.com/33217105/73232701-08c66480-41bf-11ea-8489-78b65dfb36a5.png)
the scale parameter delta in formula (1) should have been sqrt, but I don't see any sign of sqrt on it, is it a mistake?

**Comment by TouvronHugo** [comment]
Hi @BluebirdStory ,
Thank you for flagging that. Formula 1 seems to me to be correct, but I think there is a little typo on the other formula which should be more like :
<img width="660" alt="Capture d’écran 2020-02-02 à 09 24 59" src="https://user-images.githubusercontent.com/49280617/73605470-f4a7ac00-459e-11ea-9433-5c786673763d.png">
I hope this answers your question, don't hesitate if you have other questions/comments.

Hugo
