### ISSUE TITLE
Trained weights

### ISSUE THREAD

**Issue by khoshsirat** [facebookresearch/FixRes#14]
How can we access the trained weights for FixEfficientNet?
I'm not able to find them on PyTorch Image Models.
Is it possible to add a sample code?

**Comment by TouvronHugo** [comment]
Hi @khoshsirat ,
We have not yet put the trained weights of FixEfficientNet on the repo. 
But you can easily reproduce our results by using the FixRes method present in this repo. 
I'm going to try to add a sample code by the end of the week.

**Comment by khoshsirat** [comment]
Well, that requires some resources (good GPU and etc.) and time.
The trained weights will help a lot.
