### ISSUE TITLE
How to change class-count for feature extraction?

### ISSUE THREAD

**Issue by edwardcho** [facebookresearch/FixRes#15]
Hello Sir.
I tested your code.
(imnet_finetune, imnet_extract).
Using your pretrained-model, I want to try training of my model. But class count of my data is 10.
How to change this of your code?

**Comment by TouvronHugo** [comment]
Hi @edwardcho ,
You only need to change the size of the output of the fc layer. For example for a ResNet-50 you have to do :
``
model.fc=nn.Linear(2048,10)
``
 and then load the weights of your model:
``
model.load_state_dict(torch.load(PATH))
``
Normally there is nothing else to change,  the number of classes is normally only used in model definition.
