### ISSUE TITLE
Can you provide the pre-trained weight of FixEfficientNet-b4?

### ISSUE THREAD

**Issue by KoalaSheep** [facebookresearch/FixRes#17]
Thank you for your share of the code and pre-trained network FixEfficientNet-B0 and FixEfficientNet-L2. 
My case is that my gpu isn't good enough to reproduce your result and FixEfficientNet-L2 is too large for my research. It will be helpful if you can provide the pre-trained weight of FixEfficientNet-b4 and if possible other FixEfficientNet. 
By the way, I am not clear about how to load the weight of the provided FixEfficientNet because I can't find the pth file.

**Comment by TouvronHugo** [comment]
Hi @KoalaSheep ,
Unfortunately for the moment we cannot provide the pre-trained weight of the FixEfficientNet.  Nevertheless, you can reproduce our results by a finetuning of EfficientNet (Noisy Student) (PyTorch weight available on https://github.com/rwightman/pytorch-image-models) with our method (https://arxiv.org/abs/2003.08237). 
Have a good day,
Hugo
