### ISSUE TITLE
A question about your update at Aug 17. 

### ISSUE THREAD

**Issue by KoalaSheep** [facebookresearch/FixRes#24]
Thank you for add EfficientNet into your imnet_finetune/train.py and imnet_finetune/config.py

I just noticed that default_cfgs is utilized here:
`pretrained_dict=load_state_dict_from_url(default_cfgs[self._train_cfg.EfficientNet_models]['url'],map_location='cpu')`
in line 189 in imnet_finetune/train.py, which is an error in my machine. 

I wonder if 
`from timm.models.efficientnet import default_cfgs`
is missed here.

**Comment by TouvronHugo** [comment]
Hi @KoalaSheep ,
You're absolutely right, I added the missing line.
Best,

Hugo
