### ISSUE TITLE
How to use FixRes on custom dataset

### ISSUE THREAD

**Issue by mehdikhanahmadzadeh** [facebookresearch/FixRes#29]
Hi,
Can we use this model for custom datasets ? If it can be used, will it increase accuracy more than efficientnet architecture?
Or it is used only for imagenet datasets?

**Comment by TouvronHugo** [comment]
Hi @mehdikhanahmadzadeh ,

Yes, you can use FixRes on a custom dataset and also on EfficientNet architecture to improve accuracy.
I hope I have answered your question, don't hesitate if you have other questions.

Best,
Hugo

**Comment by mehdikhanahmadzadeh** [comment]
thank you very much indeed @TouvronHugo .
and in the main_finetune.py file what is a 'shared_folder' and What is inside this folder??
