### ISSUE TITLE
what is the 'shared_folder' in  main_finetune.py file?

### ISSUE THREAD

**Issue by mehdikhanahmadzadeh** [facebookresearch/FixRes#30]
thank you very much indeed @TouvronHugo .
and in the main_finetune.py file what is a 'shared_folder' in the following code ?

parser.add_argument('--shared-folder-path', default='your/shared/folder', type=str, help='Shared Folder')

**Comment by TouvronHugo** [comment]
Hi @mehdikhanahmadzadeh ,

This is the folder where the logs are saved. You can remove it if you want, it's not important.

Best,

Hugo
