### ISSUE TITLE
How can we load the labels in the validation dataset?

### ISSUE THREAD

**Issue by smiles724** [facebookresearch/FixRes#32]
Hi, I am confused about loading the labels from the ImageNet Val.

I notice that you used "dataset.Imagefolder" to load both the train and validation dataset, which requires the pictures are divided into different folders of their own types. However, when I downloaded the ImageNet dataset, I found the labels of the validation are contained in a text file while all 50k images are put in one same folder. Therefore, will this cause any problem when running the code?

I hope I made my question clear to you, thx.

**Comment by TouvronHugo** [comment]
Hi @Wufang1997 ,
Thank you for your question,
Indeed, in order to run our code you need to separate train and val into two separate folders and each class need to be in its own subfolder.
I hope I have answered your question and don't hesitate if you have other questions.

Best,

Hugo

**Comment by smiles724** [comment]
Thank you for your reply. However, the data I downloaded from the ImageNet official website doesn't meet the requirement of your code since they are not grouped in folders. Can you tell me the resource where you get your standard ImageNet dataset? So I might immediately use your provided dataset instead of modifying the code myself. 

thx!
