### ISSUE TITLE
One question from the paper

### ISSUE THREAD

**Issue by huangh12** [facebookresearch/FixRes#36]
Hi @TouvronHugo , thanks for the insightful work. I am reading the paper and have a question. Hope you can give some help.

In section 3.3, multiple K_{test} of ResNet-50 is evaluated on ImageNet. I suppose the K_{test} here is just the crop size, the K^{image}\_{test} however is unknown.   I am curions how you adjust the K^{image}\_{test} for each K_{test} in the experiments. Because it is the difference of K^{image}\_{test} that will influence the train&test calibration of object size distribution.
![图片](https://user-images.githubusercontent.com/18748036/113243787-3ee10600-92e6-11eb-81da-eb809e7ed718.png)

Thank you.

**Comment by TouvronHugo** [comment]
Hi @huangh12 ,
Thanks for your question,
K_{test} is the image size after resize and center crop. 
For instance K_{test} = 64 => Resize((256/224) x 64), CenterCrop(64)
Best,
Hugo

**Comment by huangh12** [comment]
Thank you, it's very helpful!
