### ISSUE TITLE
how to train FixResNeXt-101 32x48d ?

### ISSUE THREAD

**Issue by iot-hunter** [facebookresearch/FixRes#7]

**Comment by TouvronHugo** [comment]
Hi @iot-hunter ,
You have to download the ImageNet dataset and refer to the Readme part « Fine-tuning existing network with our Method »

Hugo

**Comment by iot-hunter** [comment]
@TouvronHugo  i am a newer to pytorch ! can it train my custom dataset ? like DeepFashion dataset? if can do that ,what should i do ?  thanks a lot

**Comment by TouvronHugo** [comment]
To do transfer-learning with our model, refer to our article part: "5.3 Transfer learning tasks". The FixResNeXt-101 32x48d is a very efficient model but requires a large enough computing infrastructure to be used in the best way for a transfer learning task. Therefore,  I advise you to use our fine-tuning method with a smaller model that you will have already trained on your dataset. What I also advise to you is to read the train.py file in the imnet_finetune folder. Our method being quite simple, the easiest way to adapt it to your dataset is to add the lines of code that correspond to our method in your code that already works on your dataset.

Hugo

**Comment by iot-hunter** [comment]
thanks a lot !!!  I will take a test
