### ISSUE TITLE
Is this git only for distribute processing?

### ISSUE THREAD

**Issue by Esaada** [facebookresearch/FixRes#8]
As the code looks like, it doesn't seem to have an option  to make a non distrbuted processing, if I'm wrong how to do I disable every related clust/dist option?

**Comment by TouvronHugo** [comment]
Hi @BarakBat 

If you want to use the code with only 1 GPU and 1 CPU you can specify it with the parameters: num-tasks and workers. But this will not allow you to reproduce our results, for example, you may not have the same batch size as ours. For the evaluation part, using only one GPU works well. Don't hesitate if you have any further questions.

Hugo

**Comment by Esaada** [comment]
I have 8 gpus and enough gpu on 1 machine that I'm working straight on, that's doesn't mean that I want to use distributed computing which is different from using multiple hw components on one machine.........

I got errors on lines that relates to the distributed, such as:
![image](https://user-images.githubusercontent.com/23050230/69005662-f95cac80-092d-11ea-9a8b-c811f904f64b.png)

**Comment by TouvronHugo** [comment]
Ok, I better understand your question. Unfortunately, there is no option to make a non distributed processing. If you want to use the code without this part, you will have to recode this. (Maybe the easiest way is to take the transformations from the transforms.py file and take the main part of the train.py file and add them in one of your training codes on ImageNet already functional.)
I hope I have answered your question,

**Comment by Esaada** [comment]
Perfectly answering my question, Thanks.

**Comment by abduallahmohamed** [comment]
@Esaada  Were you able to adapt the code for a single machine?
